### ISSUE TITLE
（（（

### ISSUE THREAD

**Issue by undefined-moe** [water-lift/oss#1]
https://img.masnn.io:38443/

建议在页面添加以下脚本并使用https://image.masnn/链接。

```js
jQuery(document).ready(function($) {
    for (let i of document.getElementsByTagName('img'))
         i.src=i.src.replace(/https:\/\/image\.masnn\//i, 'https://img.masnn.io:38443/images/');
});
```

**Comment by AsakuraMizu** [comment]
草

~~真就强行安利啊~~

**Comment by AsakuraMizu** [comment]
干脆 masnn://image/ 多好（（（

**Comment by undefined-moe** [comment]
您好，试过了
浏览器会在控制台打出 unknown protocol

**Comment by AsakuraMizu** [comment]
什



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "undefined"; 
发送时间: 2020年4月6日(星期一) 上午10:34
收件人: "water-lift/oss";
抄送: "water_lift"<2677294549@qq.com>;"Comment";
主题: Re: [water-lift/oss] （（（ (#1)





 
您好，试过了
 浏览器会在控制台打出 unknown protocol
 
&mdash;
